apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
        - setweight: 20
        - pause:
            duration: 20s

        - setweight: 50
        - pause:
            duration: 20s

        - setweight: 100
  selector:
    matchLables:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        portS:
        - containerPort: 80
        redinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
